version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"

# Each subfolder needs to be checked separately
  - package-ecosystem: docker
    directory: "/postgresql"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"
  - package-ecosystem: docker
    directory: "/sda-download"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"
  - package-ecosystem: docker
    directory: "/rabbitmq"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"
  - package-ecosystem: docker
    directory: "/sda"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"
  - package-ecosystem: docker
    directory: "/sda-sftp-inbox"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"

# Each subfolder needs to be checked separately
  - package-ecosystem: gomod
    directory: "/sda"
    groups:
      all-modules:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"
    schedule:
      interval: "weekly"

  - package-ecosystem: gomod
    directory: "/sda-download"
    groups:
      all-modules:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"
    schedule:
      interval: weekly

# Each subfolder needs to be checked separately
  - package-ecosystem: maven
    directory: "/sda-sftp-inbox"
    groups:
      all-modules:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"
    schedule:
      interval: weekly

  - package-ecosystem: maven
    directory: "/sda-doa"
    groups:
      all-modules:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/sda-doa"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"

## release v1 branch
### Docker
  - package-ecosystem: docker
    target-branch: release_v1
    directory: "/postgresql"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"

  - package-ecosystem: docker
    target-branch: release_v1
    directory: "/rabbitmq"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"

  - package-ecosystem: docker
    target-branch: release_v1
    directory: "/sda"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"

  - package-ecosystem: docker
    target-branch: release_v1
    directory: "/sda-doa"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"

  - package-ecosystem: docker
    target-branch: release_v1
    directory: "/sda-download"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"

  - package-ecosystem: docker
    target-branch: release_v1
    directory: "/sda-sftp-inbox"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"

### JAVA
  - package-ecosystem: maven
    target-branch: release_v1
    directory: "/sda-doa"
    groups:
      all-modules:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"
    schedule:
      interval: daily

  - package-ecosystem: maven
    target-branch: release_v1
    directory: "/sda-sftp-inbox"
    groups:
      all-modules:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"
    schedule:
      interval: daily
### GO
  - package-ecosystem: gomod
    target-branch: release_v1
    directory: "/sda-download"
    groups:
      all-modules:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"
    schedule:
      interval: daily

  - package-ecosystem: gomod
    target-branch: release_v1
    directory: "/sda"
    groups:
      all-modules:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    reviewers:
      - "neicnordic/sensitive-data-development-collaboration"
    schedule:
      interval: daily
