{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sda.fullname" . }}-api
  labels:
    app: {{ template "sda.fullname" . }}-api
spec:
  ports:
  - name: api
    port: 8080
    targetPort: api
    protocol: TCP
  selector:
    app: {{ template "sda.fullname" . }}-api
{{- end }}
