{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not .Values.global.deploymentType)}}
{{- if not .Values.global.vaultSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-api
type: Opaque
data:
  dbPassword: {{ required "DB password is required" (include "dbPassAPI" .) | b64enc }}
  dbUser: {{ required "DB user is required" (include "dbUserAPI" .) | b64enc }}
  mqPassword: {{ required "MQ password is required" (include "mqPassAPI" .) | b64enc }}
  mqUser: {{ required "MQ user is required" (include "mqUserAPI" .) | b64enc }}
---
{{- if not .Values.global.api.adminsFileSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-api-admins
type: Opaque
data:
  admins.json: {{ .Values.global.api.adminUsers | toJson | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
