apiVersion: v2
name: sda-svc
version: "0.21.0"
appVersion: "v0.0.75"
kubeVersion: ">= 1.19.0-0"
description: Components for Sensitive Data Archive (SDA) installation
home: https://neic-sda.readthedocs.io
icon: https://neic.no/assets/images/logo.png
sources:
- https://github.com/neicnordic/sensitive-data-archive
