log:
  format: "json"
  level: "debug"
archive:
  type: s3
  url: "http://s3"
  port: 9000
  readypath: "/minio/health/ready"
  accessKey: "access"
  secretKey: "secretKey"
  bucket: "archive"
  region: "us-east-1"
backup:
  type: s3
  url: "http://s3"
  port: 9000
  readypath: "/minio/health/ready"
  accessKey: "access"
  secretKey: "secretKey"
  bucket: "backup"
  region: "us-east-1"
inbox:
  type: s3
  url: "http://s3"
  port: 9000
  readypath: "/minio/health/ready"
  accessKey: "access"
  secretKey: "secretKey"
  bucket: "inbox"
  region: "us-east-1"

broker:
  host: "rabbitmq"
  port: "5672"
  user: ""
  password: ""
  vhost: "/sda"
  exchange: "sda"
  routingKey: ""
  ssl: "false"

db:
  host: "postgres"
  port: "5432"
  user: ""
  password: ""
  database: "sda"
  sslmode: "disable"

c4gh:
  filePath: /shared/c4gh.sec.pem
  passphrase: "c4ghpass"

server:
  cert: ""
  key: ""
  jwtpubkeypath: "/shared/keys/pub/"
  jwtpubkeyurl: "http://oidc:8080/jwk"


