name: integration tests
on: [pull_request]

env:
  svc_list: 'finalize inbox ingest mapper verify'

jobs:
  integrationtests:
    name: integration
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run setup scripts
        run: 'set -e;
              ls -1 .github/integration/setup/*.sh 2>/dev/null | sort -t/ -k5 -n | while read -r runscript; do
                 echo "Executing setup script $runscript";
                 bash -x "$runscript";
              done'

      - name: Run tests
        run: 'ls -1 .github/integration/tests/*.sh 2>/dev/null | sort -t/ -k5 -n | while read -r runscript; do
                echo "Executing test script $runscript";
                bash -x "$runscript";
              done'
